---
apiVersion: v1
data:
  telegramtoken: xxxxxxtelegramxxxxtokenxxxx
kind: Secret
metadata:
  name: telegramtoken
type: Opaque
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager-config
  labels:
    alertmanagerConfig: thisnamehastomatch
spec:
  route:
    groupBy: ['job','alertname']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: 'telegram'
    routes:
      - groupBy: ['job','alertname']
        groupWait: 30s
        groupInterval: 5m
        repeatInterval: 12h
        receiver: 'blackhole'
        matchers:
        - name: alertname
          value: InfoInhibitor
  receivers:
  - name: telegram
    telegramConfigs:
    - botToken:
        name: telegramtoken
        key: telegramtoken
      chatID: -12345678
      apiURL: "https://api.telegram.org"
      parseMode: "HTML"
  - name: blackhole
