apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  name: easterhegg21
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: Namespace
      metadata:
        # name in manifest is optional and defaults to Object name
        # name: some-other-name
        labels:
          easgterhegg: "true"
          specialApp: "true"
  providerConfigRef:
    name: easterhegg21
