prometheus:
  ingress:
    enabled: true
    hosts:
    - prometheus-127-0-0-1.nip.io
    tls:
    - hosts:
      - "prometheus-127-0-0-1.nip.io"
      secretName: prometheus-127-0-0-1-nip-io
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      cert-manager.io/cluster-issuer: "selfsigned-issuer"
  logLevel: debug
alertmanager:
  enabled: true
  ingress:
    enabled: true
    hosts:
    - alertmanager-127-0-0-1.nip.io
    tls:
    - hosts:
      - "alertmanager-127-0-0-1.nip.io"
      secretName: alertmanager--127-0-0-1-nip-io
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      cert-manager.io/cluster-issuer: "selfsigned-issuer"
  alertmanagerSpec:
    alertmanagerConfigSelector:
      matchExpressions:
        - key: alertmanagerConfig
          operator: In
          values:
            - thisnamehastomatch
grafana:
  persistence:
    enabled: true
  imageRenderer:
    enabled: true
  adminPassword: password123
  ingress:
    enabled: true
    hosts:
    - grafana-127-0-0-1.nip.de
    tls:
    - hosts:
      - "grafana-127-0-0-1.nip.io"
      secretName: grafana--127-0-0-1-nip-io
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      cert-manager.io/cluster-issuer: "selfsigned-issuer"
  env:
    GF_DATE_FORMATS_INTERVAL_DAY: "MMM YYYY"